

all:
	g++ Principal.cpp Controlador.cpp -I//home/computacion/opencv/opencvi/include/opencv4 -L/home/computacion/opencv/opencvi/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -o objDetection   -lopencv_objdetect -o vision.bin


run:
	./vision.bin